services:
  web:
    build:
      dockerfile: dockerfile
      context: .
    command: gunicorn django_recap.wsgi:application --bind 0.0.0.0:8000 --reload
    env_file:
      - .env
    volumes:
      - .:/workspace
    port:
      8000:8000
    database:
      image: postgres:alpine
      env_file:
        - .env
